__TOKEN__ = 'NTE0MTAwNDE5Nzk1MDkxNDc3.DtRr-w.bbhC5it6LykZsU8upnzBTwnfcfY'

__main_domain__ = 'http://taskbox.zzz.com.ua/pr/'

__get_all_tasks_url__ = __main_domain__ + 'get_all_tasks.php'
__reg_url__ = __main_domain__ + 'reg.php'
__push_task_url__ = __main_domain__ + 'push_task.php'
__validate_url__ = __main_domain__ + 'validate.php'
__discard_url__ = __main_domain__ + 'discard.php'
__get_user_url__ = __main_domain__ + 'get_user.php'
__get_tasklist_url__ = __main_domain__ + 'tasks/show_tasks.php'
__get_phase_by_id_url__ = __main_domain__ + 'get_phase_by_id.php'
__get_max_points_url__ = __main_domain__ + 'get_max_points.php'
__change_lang_url__ = __main_domain__ + 'change_lang.php'
__add_item_url__ = __main_domain__ + 'add_item.php'
__get_inventory_url__ = __main_domain__ + 'get_inventory.php'
__remove_item_url__ = __main_domain__ + 'remove_item.php'
__get_item_info_url__ = __main_domain__ + 'get_item_info.php'
__check_ach_in_voice_url__ = __main_domain__ + 'check_ach_in_voice.php'
__add_achievement_url__ = __main_domain__ + 'add_achievement.php'
__get_ach_list_url__ = __main_domain__ + 'get_ach_list.php'
