__TOKEN__ = 'NTE0MTAwNDE5Nzk1MDkxNDc3.DtRr-w.bbhC5it6LykZsU8upnzBTwnfcfY'

__get_all_tasks_url__ = 'http://taskbox.zzz.com.ua/pr/get_all_tasks.php'
__reg_url__ = 'http://taskbox.zzz.com.ua/pr/reg.php'
__push_task_url__ = 'http://taskbox.zzz.com.ua/pr/push_task.php'
__validate_url__ = 'http://taskbox.zzz.com.ua/pr/validate.php'
__discard_url__ = 'http://taskbox.zzz.com.ua/pr/discard.php'
__get_user_url__ = 'http://taskbox.zzz.com.ua/pr/get_user.php'
__get_tasklist_url__ = 'http://taskbox.zzz.com.ua/pr/tasklist.html'
__get_phase_by_id_url__ = 'http://taskbox.zzz.com.ua/pr/get_phase_by_id.php'
__get_max_points__ = 'http://taskbox.zzz.com.ua/pr/get_max_points.php'
__change_lang__ = 'http://taskbox.zzz.com.ua/pr/change_lang.php'
